server:
  port: 9999

spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
      client:
        health-indicator:
          enabled: true
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8081"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
      enabled: true
      filter:
        prefix-path:
          enabled: true
      routes:
        - id: product-service
          uri: http://localhost:8189
          predicates:
            - Path=/products/**
          filters:
            - PrefixPath=/market-core/api/v1
        - id: auth-service
          uri: http://localhost:8189
          predicates:
            - Path=/auth/**
          filters:
            - PrefixPath=/market-core/api/v1
        - id: cart-service
          uri: http://localhost:8189
          predicates:
            - Path=/cart/**
          filters:
            - PrefixPath=/market-core/api/v1
        - id: order-service
          uri: http://localhost:8191
          predicates:
            - Path=/order/**
          filters:
            - PrefixPath=/market-order/api/v1
logging:
  level:
    reactor:
      netty: TRACE
    org:
      springframework:
        cloud:
          gateway: TRACE