server:
  port: 8191
  servlet:
    context-path: /market-order
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5440/wsdb
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
integration:
  services:
    cart:
      uri: http://localhost:8189/market-core/api/v1/cart
