server:
  port: 8189
  servlet:
    context-path: /market-core
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5440/wsdb
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
jwt:
  secret: kvb789bv8974bdsa9wqyH87fweyHXIL7*7*&&78tgFc87trfA&BCI&lbb7##jF*y
  lifetime: 3600000 # 1 Hour

